[tool.black]
line-length = 120
target-version = ['py311']
# force-exclude = '''test'''

[tool.coverage.run]
omit = ["tests/*"]

[tool.mypy]
check_untyped_defs = true
exclude = "tests"
ignore_missing_imports = true
python_version = "3.11"
packages = ["src"]
explicit_package_bases = true
disable_error_code = ["import-untyped"]
