variable "aws_region" {}
variable "vpc_id" {}
variable "vpc_endpoint" {}
variable "resource_prefix" {}
variable "lambda_role_arn" {}
variable "lambda_vpc_subnet_ids" {}
variable "lambda_package_type" {}
variable "lambda_src_s3_bucket" {}
variable "lambda_src_s3_key" {}
variable "lambda_src_ecr_image" {}
