name: Trivy Full Repository Scan

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  security-events: write

jobs:
  trivy:
    name: Trivy Full Repository Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Setup Trivy
        uses: aquasecurity/setup-trivy@v0.2.4

      - name: Run Trivy filesystem scan
        run: |
          trivy fs . \
            --format sarif \
            --scanners vuln,secret,misconfig,license \
            --output trivy_repository_report.sarif

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: trivy_repository_report.sarif
